#48 feature/21
f-lab-edu/food-delivery pull request #49
Opened 2019-12-04 08:52 UTC by binaryyoung

2019-12-04 08:56 UTC, binaryyoung commented on src/main/resources/mybatis/mapper/coupon.xml
> +		</selectKey>
`selectKey`를 이용해서 `LocalDateTime`을 반환하려고 하는데 다음과 같은 예러가 발생합니다.

```
{
    "timestamp": "2019-12-04T08:42:44.776+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Mapper method 'com.delfood.mapper.CouponMapper.insertCoupon' has an unsupported return type: class java.time.LocalDateTime",
    "path": "/coupons/"
}
```

어떻게 해결할 수 있을까요?

2019-12-06 13:41 UTC, f-lab-dev commented on src/main/resources/mybatis/mapper/coupon.xml
> +		</selectKey>
이거는 마이바티스 자체에서 `LocalDateTime`을 지원안하는 문제로 보입니다. 마이바티스 버전을 올리면 해결 가능한지 찾아보거나 `Date`로 리턴받고` LocalDateTime`으로 바꿔주셔야겠네요.

2019-12-06 15:02 UTC, f-lab-dev commented on src/main/java/com/delfood/dto/CouponDTO.java
> +  public static boolean hasNullDataBeforeAdd(CouponDTO couponInfo) {
`BeforeAdd`는 이 메소드의 동작에 관련없는 동작이니 빼는게 좋을 것 같습니다~

2019-12-06 15:02 UTC, f-lab-dev commented on src/main/java/com/delfood/service/CouponService.java
> +      throw new RuntimeException("coupon expiration date is ealire than creation date!");
더 자세한 예외타입으로 써줄 수 있을 것 같습니다

2019-12-12 12:38 UTC, f-lab-dev commented on src/main/java/com/delfood/dto/CouponDTO.java
> +    return couponInfo.getName() == null || couponInfo.getDiscountType() == null
만약 이 값들이 null값을 가지면 안됀다면 필드에 `@NotNull`을 써보는건 어떨까요?

2019-12-12 12:38 UTC, f-lab-dev commented on src/main/java/com/delfood/service/CouponService.java
> +      throw new DateTimeException("coupon expiration date is ealire than creation date!");
이거는 쿠폰이 만료된 상태라 사용이 불가능한 상태이기에 `IllegalStateException`을 날려줘도 괜찮을 것 같습니다. 최대한 자바 표준예외를 사용하고, 적절한게 없을 때 커스텀 예외를 날리는게 좋습니다.

2019-12-12 12:38 UTC, f-lab-dev commented on src/main/java/com/delfood/service/CouponService.java
> +      throw new RuntimeException("coupon update error!");
`result != 0`이면 업데이트 되었을 때에도 예외가 발생할 것 같습니다.

2019-12-12 12:38 UTC, f-lab-dev commented on src/main/java/com/delfood/service/CouponService.java
> +    if (couponIssueService.isIssued(id)) {
적절한 로직인 것 같습니다. 이미 발행된 쿠폰이 있으면 기록을 남기기위해 삭제해서는 안됍니다~

2019-12-12 12:38 UTC, f-lab-dev commented on src/main/resources/mybatis/mapper/couponIssue.xml
> +        LIMIT 1
count(*)은 결과가 1개뿐일텐데 limit은 필요 없을 것 같습니다~

2019-12-13 04:50 UTC, yyy9942 reviewed
고생하셨습니다.

2019-12-13 04:50 UTC, yyy9942 commented on src/main/java/com/delfood/controller/CouponController.java
>      return HttpStatus.OK;
200 Status만 반환하는 결과라면 굳이 `HttpStatus` 를 반환할 필요는 없을것같습니다.
리턴타입을 void로 해둬도 status값은 200(OK)로 오니까요.

2019-12-13 04:50 UTC, yyy9942 commented on src/main/java/com/delfood/mapper/CouponMapper.java
> +  public int updateCouponNameAndEndAt(Long id, String name, LocalDateTime endAt);
쿠폰 수정이라고 주석이 달려있는데 정확히 어떤 컬럼이 수정되는지 적어주실 수 있을까요? 이름과 만료일만 수정이 가능한건가요?

2019-12-13 04:50 UTC, yyy9942 commented on src/main/resources/mybatis/mapper/coupon.xml
> +        AND endAt = #{endAt}
DB 속성은 end_at으로 되어있습니다. 해당 형식으로 쿼리를 날리면 오류가 날거같습니다.

2019-12-16 14:33 UTC, f-lab-dev commented on src/main/java/com/delfood/service/CouponIssueService.java
> +    if (result != 1) {
이제 이런 조건들도 걷어낼 때가 된 것 같습니다. memberId와 couponId가 유효한지는 insert하기 전에 이미 검증이 되어있어야하기 때문입니다~

2019-12-18 03:51 UTC, binaryyoung commented on src/main/java/com/delfood/service/CouponIssueService.java
> +    if (result != 1) {
이 부분을 걷어 내고 미리 값의 유효성을 검증하는 로직을 더 꼼꼼히 작성하면 되는걸까요?

2019-12-19 11:54 UTC, f-lab-dev commented on src/main/java/com/delfood/service/CouponIssueService.java
> +    if (result != 1) {
네 맞습니다~ insert문이 제대로 작성되어있고, 파라미터가 잘 검사되어있으면 이런 일은 일어나지 않을테니까요

2019-12-23 12:01 UTC, f-lab-dev approved these changes

2019-12-23 12:02 UTC, f-lab-dev requested changes
잘못 approve 했네요

2020-01-03 14:38 UTC, f-lab-dev approved these changes
머지해도 괜찮을 것 같네요~ 남은 리뷰 1개만 나중에 고치면 좋을 것 같습니다

2020-02-10 09:03 UTC, merged